AllCops:
  DisplayCopNames: true
  DisplayStyleGuide: true
  NewCops: disable
  SuggestExtensions: false
  AutoCorrect: true
  Exclude:
    - "vendor/**/*"
    - "bin/**/*"
    - "db/schema.rb"
    - "node_modules/**/*"
    - "public/**/*"
    - "scratchpad.rb"
    - "native/**/*"

Style/FrozenStringLiteralComment:
  Enabled: false

GraphQL/FieldDescription:
  Enabled: false

GraphQL/ObjectDescription:
  Enabled: false

GraphQL/ArgumentDescription:
  Enabled: false
