require:
  - rubocop-graphql
  - standard

inherit_gem:
  standard: config/base.yml

AllCops:
  DisplayCopNames: true
  DisplayStyleGuide: true
  NewCops: disable
  SuggestExtensions: false
  AutoCorrect: true
  Exclude:
    - "vendor/**/*"
    - "bin/**/*"
    - "db/schema.rb"
    - "tmp/storage/**/*"
    - "tmp/cache/**/*"
    - "storage/**/*"
    - "node_modules/**/*"
    - "public/**/*"
    - "scratchpad.rb"
    - "native/**/*"

Style/FrozenStringLiteralComment:
  Enabled: false

GraphQL/FieldDescription:
  Enabled: false

GraphQL/ObjectDescription:
  Enabled: false

GraphQL/ArgumentDescription:
  Enabled: false

GraphQL/ExtractType:
  Enabled: false

GraphQL/MaxDepthSchema:
  Enabled: false

GraphQL/MaxComplexitySchema:
  Enabled: false

GraphQL/ExtractInputType:
  Enabled: false
