services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        RUBY_VERSION: "3.3"
        NODE_VERSION: "20.10.0"

    volumes:
      - ../..:/workspaces:cached
      - ~/.netrc:/root/.netrc
      - ~/.ssh:/root/.ssh
      - ~/.config/gh:/root/.config/gh
      - ~/.aws:/root/.aws
      - ~/Music:/app/music:ro

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

    # Runs app on the same network as the database container, allows "forwardPorts" in devcontainer.json function.
    network_mode: service:db

    environment:
      TZ: Europe/Berlin
      EDITOR: code --wait
  db:
    image: postgres:16.4
    restart: unless-stopped
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
  redis:
    image: redis
    restart: unless-stopped
    ports:
      - 6379:6379
    volumes:
      - redis:/data
  elasticsearch:
    image: elasticsearch:8.11.1
    restart: always
    ports:
      - 9200:9200
    volumes:
      - elasticsearch:/usr/share/elasticsearch/data
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
volumes:
  postgres:
  elasticsearch:
  redis:
