services:
  db:
    image: postgres:15
    restart: always
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
  redis:
    image: redis
    restart: always
    ports:
      - 6379:6379
    volumes:
      - redis:/data
  elasticsearch:
    image: elasticsearch:8.11.1
    restart: always
    ports:
      - 9200:9200
    volumes:
      - elasticsearch:/usr/share/elasticsearch/data
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
volumes:
  postgres:
  redis:
  elasticsearch:
