// export * from './mutations/add_like_to_recording'
export * from './mutations/apple_login'
// export * from './mutations/create_playback'
export * from './mutations/google_login'
export * from './mutations/login'
export * from './mutations/register'
// export * from './mutations/remove_like_from_recording'
// export * from './queries/check_like_status_on_recording'
// export * from './queries/composers'
export { CURRENT_USER } from './queries/current_user'
export { USER_PROFILE } from './queries/user_profile'
// export * from './queries/fetch_composer'
// export * from './queries/fetch_user'
// export * from './queries/liked_recordings'
// export * from './queries/lyricist'
// export * from './queries/lyricists'
// export * from './queries/orchestra'
export * from './queries/orchestras'
// export * from './queries/playlist'
export * from './queries/playlists'
// export * from './queries/recording'
export * from './queries/recordings'
// export * from './queries/singer'
// export * from './queries/singers'
export * from './queries/tanda_of_the_week'
// export * from './queries/whoAmI'
// export { default as REGISTER } from './mutations/register'
// export { default as LOGIN } from './mutations/login'
// export { default as GOOGLE_LOGIN } from './mutations/google_login'
// export { default as APPLE_LOGIN } from './mutations/apple_login'
