# image not running the latest arm64 version of ubuntu
FROM mcr.microsoft.com/vscode/devcontainers/base:ubuntu-22.04

ENV RAILS_DEVELOPMENT_HOSTS=".githubpreview.dev,.app.github.dev"

SHELL ["/bin/bash", "-o", "pipefail", "-c"]
