default: &default
  adapter: postgresql
  encoding: unicode
  host: 127.0.0.1
  pool: <%= ENV["DB_POOL"] || ENV["RAILS_MAX_THREADS"] || 5 %>
  username: postgres
  port: 5432
  variables:
    statement_timeout: <%= ENV["STATEMENT_TIMEOUT"] || 30000 %>

sqlite_default: &sqlite_default
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 10 } %>
  timeout: 5000

development:
  primary: &primary_development
    <<: *default
    database: tangocloud_development

test:
  primary: &primary_test
    <<: *default
    database: tangocloud_test

production:
  primary: &primary_production
    <<: *default
    host: <%= ENV["DB_HOST"] %>
    database: tangocloud_production
    password: <%= ENV["POSTGRES_PASSWORD"] %>

  cache: &cache_production
    <<: *sqlite_default
    database: storage/tangocloud_production_cache
    migrations_paths: db/cache_migrate

  queue: &queue_production
    <<: *sqlite_default
    database: storage/reference_rails_production_queue
    migrations_paths: db/queue_migrate
