default: &default
  adapter: postgresql
  encoding: unicode
  host: 127.0.0.1
  pool: <%= ENV["DB_POOL"] || ENV["RAILS_MAX_THREADS"] || 5 %>
  username: postgres
  port: 5432
  variables:
    statement_timeout: <%= ENV["STATEMENT_TIMEOUT"] || 30000 %>

development:
  primary: &primary_development
    <<: *default
    database: tangocloud_development
  queue:
    <<: *default
    database: tangocloud_development_queue
    migrations_paths: db/queue_migrate
  cache:
    <<: *default
    database: tangocloud_production_cache
    migrations_paths: db/cache_migrate

test:
  primary: &primary_test
    <<: *default
    database: tangocloud_test

production:
  primary: &primary_production
    <<: *default
    host: <%= ENV["DB_HOST"] %>
    database: tangocloud_production
    password: <%= ENV["POSTGRES_PASSWORD"] %>
  queue:
    <<: *primary_production
    database: tangocloud_production_queue
    migrations_paths: db/queue_migrate
  cache:
    <<: *primary_production
    database: tangocloud_production_cache
    migrations_paths: db/cache_migrate
