default: &default
  adapter: postgresql
  encoding: unicode
  host: 127.0.0.1
  port: 54315
  pool: <%= ENV["DB_POOL"] || ENV["RAILS_MAX_THREADS"] || 5 %>
  username: <%= ENV["PG_USER"] || "postgres" %>
  variables:
    statement_timeout: <%= ENV["STATEMENT_TIMEOUT"] || 60000 %>

development:
  <<: *default
  database: tangocloud_development

test:
  <<: *default
  database: tangocloud_test

production:
  <<: *default
  host: <%= ENV["DB_HOST"] %>
  database: tangocloud_production
  password: <%= ENV["POSTGRES_PASSWORD"] %>
  port: 5432
