service: tangocloud

image: jmarsh24/tangocloud

servers:
  web:
    hosts:
      - 94.130.104.7
    cmd: bundle exec puma -C /rails/config/puma.rb
  worker:
    hosts:
      - 195.201.147.15
    cmd: bundle exec good_job execute
registry:
  server: ghcr.io
  username:
    - KAMAL_REGISTRY_USERNAME
  password:
    - KAMAL_REGISTRY_PASSWORD
env:
  clear:
    KAMAL_CONTAINER_NAME: tangocloud
    HOST: tangotube.tv
    RAILS_ENV: production
    RAILS_LOG_TO_STDOUT: true
    DB_HOST: 167.235.70.96
  secret:
    - RAILS_MASTER_KEY
    - POSTGRES_PASSWORD
accessories:
  db:
    image: postgres:15
    host: 167.235.70.96
    port: 5432
    env:
      clear:
        POSTGRES_USER: "postgres"
        POSTGRES_DB: "tangotube_production"
      secret:
        - POSTGRES_PASSWORD
    files:
      - config/postgres/production.conf:/var/postgres/data/postgresql.conf
    volumes:
      - /var/postgres/data:/var/lib/postgresql/data
builder:
  multiarch: false
healthcheck:
  log_lines: 10_000
