service: tangocloud

image: jmarsh24/tangocloud

servers:
  web:
    hosts:
      - 167.235.70.96
    cmd: bundle exec puma -C /rails/config/puma.rb
registry:
  server: ghcr.io
  username:
    - KAMAL_REGISTRY_USERNAME
  password:
    - KAMAL_REGISTRY_PASSWORD
env:
  clear:
    KAMAL_CONTAINER_NAME: tangocloud
  secret:
    - RAILS_MASTER_KEY

builder:
  multiarch: false

healthcheck:
  log_lines: 10_000
