default: &default
  store_options:
    max_age: <%= 1.month.to_i %>
    max_size: <%= 256.megabytes %>
    namespace: <%= Rails.env %>
development:
  database: cache
  <<: *default
test:
  <<: *default
production:
  database: cache
  <<: *default
