// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAudioFilesInFolder(arg1) {
  return window['go']['main']['App']['GetAudioFilesInFolder'](arg1);
}

export function GetFoldersInFolder(arg1) {
  return window['go']['main']['App']['GetFoldersInFolder'](arg1);
}

export function GetMatchingRecords(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['main']['App']['GetMatchingRecords'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function GetRecordingsWithFilter(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['GetRecordingsWithFilter'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function ImportCsvFile() {
  return window['go']['main']['App']['ImportCsvFile']();
}

export function MapSong(arg1, arg2) {
  return window['go']['main']['App']['MapSong'](arg1, arg2);
}

export function PrintLog(arg1) {
  return window['go']['main']['App']['PrintLog'](arg1);
}
