service: tangocloud

image: jmarsh24/tangocloud

servers:
  web:
    hosts:
      - 94.130.104.7
  worker-1:
    hosts:
      - 195.201.147.15
    cmd: bundle exec rake solid_queue:start
  worker-2:
    hosts:
      - 195.201.147.15
    cmd: bundle exec rake solid_queue:start
registry:
  server: ghcr.io
  username:
    - KAMAL_REGISTRY_USERNAME
  password:
    - KAMAL_REGISTRY_PASSWORD
env:
  clear:
    KAMAL_CONTAINER_NAME: tangocloud
    HOST: tangocloud.app
    RAILS_ENV: production
    RAILS_LOG_LEVEL: info
    RAILS_LOG_TO_STDOUT: true
    DB_POOL: 40
    DB_HOST: 10.1.0.3
    CLOUDFLARE_BUCKET: tangocloud
    ELASTICSEARCH_URL: 10.1.0.5:9200
    CDN_HOST: https://tangocloud.app
  secret:
    - RAILS_MASTER_KEY
    - POSTGRES_PASSWORD
accessories:
  db:
    image: postgres:15
    host: 167.235.70.96
    port: 5432
    env:
      clear:
        POSTGRES_DB: "tangocloud_production"
      secret:
        - POSTGRES_PASSWORD
    files:
      - config/postgres/production.conf:/var/postgres/data/postgresql.conf
    volumes:
      - /var/postgres/data:/var/lib/postgresql/data
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.0-arm64
    host: 49.13.197.47
    port: 9200
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
    files:
      - config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    volumes:
      - /var/lib/elasticsearch/data:/usr/share/elasticsearch/data
builder:
  multiarch: false
healthcheck:
  log_lines: 10_000
