cluster.name: elastic-search
node.name: es-node-1
network.host: 0.0.0.0
discovery.type: single-node
path.data: /usr/share/elasticsearch/data
http.port: 9200
transport.port: 9300
http.cors.enabled: true
http.cors.allow-origin: "*"
xpack.security.enabled: false
xpack.security.http.ssl.enabled: false
xpack.security.transport.ssl.enabled: false
xpack.watcher.enabled: false
xpack.ml.enabled: false
xpack.graph.enabled: false
xpack.license.self_generated.type: basic
indices.query.bool.max_clause_count: 4096
