test:
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>

local:
  service: Disk
  root: <%= Rails.root.join("storage") %>

cloudflare:
  service: S3
  endpoint: https://<%= Config.cloudflare_account_id %>.r2.cloudflarestorage.com
  access_key_id: <%= Config.cloudflare_access_key_id %>
  secret_access_key: <%= Config.cloudflare_secret_access_key %>
  region: auto
  bucket: <%= Config.cloudflare_bucket %>
  public: <%= Config.cloudflare_public %>
