thumb:
  resize_to_limit: [64, 64]
  saver:
    strip: true
    quality: 75
    lossless: false
    alpha_q: 85
    reduction_effort: 6
    smart_subsample: true
  format: "webp"

small:
  resize_to_limit: [128, 128]
  saver:
    strip: true
    quality: 75\
    lossless: false
    alpha_q: 85
    reduction_effort: 6
    smart_subsample: true
  format: "webp"

medium:
  resize_to_limit: [256, 256]
  saver:
    strip: true
    quality: 75
    lossless: false
    alpha_q: 85
    reduction_effort: 6
    smart_subsample: true
  format: "webp"

large:
  resize_to_limit: [1024, 1024]
  saver:
    strip: true
    quality: 75
    lossless: false
    alpha_q: 85
    reduction_effort: 6
    smart_subsample: true
  format: "webp"
