AllCops:
  DisplayCopNames: true
  DisplayStyleGuide: true
  NewCops: disable
  SuggestExtensions: false
  AutoCorrect: true
  Exclude:
    - "vendor/**/*"
    - "bin/**/*"
    - "db/schema.rb"
    - "node_modules/**/*"
    - "public/**/*"
    - "scratchpad.rb"

inherit_gem:
  shimmer: config/rubocop_base.yml

Style/FrozenStringLiteralComment:
  Enabled: false
