source "https://rubygems.org"
ruby File.read(File.join(__dir__, ".ruby-version")).strip

# Core
gem "puma"
gem "rails", "7.1.3"

# Database
gem "pg"

# Performance
gem "bootsnap", require: false
gem "oj"

# Extensions
gem "acts_as_list"
gem "apollo_upload_server"
gem "avo"
gem "bcrypt"
gem "chunky_png"
gem "dotenv-rails"
gem "faraday"
gem "friendly_id"
gem "graphiql-rails"
gem "graphql"
gem "groupdate"
gem "jwt"
gem "kamal"
gem "kaminari"
gem "omniauth"
gem "omniauth-rails_csrf_protection"
gem "progress_bar"
gem "pundit"
gem "rack-cors"
gem "rails-i18n"
gem "socialization"
gem "solid_cache"
gem "translate_client"
gem "solid_queue"
gem "mission_control-jobs"
gem "streamio-ffmpeg"
gem "elasticsearch"
gem "searchkick"
gem "googleauth"
gem "shimmer"
gem "inline_svg"
gem "lograge"

# Assets
gem "stimulus-rails"
gem "image_processing"
gem "propshaft"
gem "ruby-vips"
gem "vite_rails"
gem "turbo-rails"

# External Services
gem "aws-sdk-s3", require: false
gem "newrelic_rpm"
gem "sentry-rails"
gem "sentry-ruby"

group :development, :test do
  gem "capybara"
  gem "capybara-playwright-driver"
  gem "debug"
  gem "i18n-tasks"
  gem "rack_session_access"
  gem "rspec-rails"
  gem "rubocop-graphql", require: false
  gem "rubocop-rails", require: false
  gem "rubocop-rspec", require: false
  gem "standard"
  gem "ruby-lsp-rspec", require: false
  gem "faker"
end

group :development do
  gem "annotate"
  gem "chusaku"
  gem "guard"
  gem "guard-rspec"
  gem "letter_opener"
  gem "pry-rails"
  gem "rb-fsevent"
  gem "web-console"
  gem "brakeman"
  gem "authentication-zero"
end

group :test do
  gem "rspec-retry"
  gem "webmock"
end
