name: CI

on: [push, pull_request]

jobs:
  scan:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./api

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true

      - name: Scan for security vulnerabilities
        run: bin/brakeman

  lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./api
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true

      - name: Lint code for consistent style
        run: bin/rubocop

  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./api
    services:
      postgres:
        image: postgres:15
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test
      elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:8.12.0
        ports:
          - 9200:9200
        options: >-
          -e "discovery.type=single-node"
          -e "xpack.security.enabled=false"
          --health-cmd "curl http://localhost:9200/_cluster/health?wait_for_status=yellow&timeout=50s"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 10

    steps:
      - name: Install packages
        run: |
          sudo apt-get update
          sudo apt-get install --no-install-recommends -y google-chrome-stable
          sudo apt-get install --no-install-recommends -y libvips42
          sudo apt-get install --no-install-recommends -y postgresql-client
          sudo apt-get install --no-install-recommends -y libpq-dev
          sudo apt-get install --no-install-recommends -y ffmpeg

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true
      - name: Check Translations
        run: bundle exec i18n-tasks health
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps chromium
      - name: Run Tests
        env:
          DATABASE_URL: postgres://postgres:postgres@127.0.0.1:5432/test
          RAILS_ENV: test
          RSPEC_RETRY_RETRY_COUNT: 3
          ELASTICSEARCH_URL: http://localhost:${{ job.services.elasticsearch.ports[9200] }}
        run: bin/rspec --format documentation
