name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true
          working-directory: ./api

      - name: Scan for security vulnerabilities
        run: bin/brakeman
        working-directory: ./api

  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true
          working-directory: ./api

      - name: Lint code for consistent style
        run: bin/rubocop
        working-directory: ./api

  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test
      elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:8.12.0
        ports:
          - 9200:9200
        options: >-
          -e "discovery.type=single-node"
          -e "xpack.security.enabled=false"
        env:
          ES_JAVA_OPTS: -Xms512m -Xmx512m
        volumes:
          - elasticsearch:/usr/share/elasticsearch/data

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install packages
        run: |
          sudo apt-get update
          sudo apt-get install --no-install-recommends -y google-chrome-stable
          sudo apt-get install --no-install-recommends -y libvips42
          sudo apt-get install --no-install-recommends -y postgresql-client
          sudo apt-get install --no-install-recommends -y libpq-dev

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: "20.x"
          cache: yarn

      - name: Install ffmpeg
        run: sudo apt-get install --no-install-recommends -y ffmpeg

      - name: Install audiowaveform
        run: |
          sudo add-apt-repository -y ppa:chris-needham/ppa
          sudo apt-get update
          sudo apt-get install -y audiowaveform

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true
          working-directory: ./api

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps chromium
        working-directory: ./api

      - name: Install Node dependencies
        run: yarn install --frozen-lockfile
        working-directory: ./api

      - name: Checkout LFS objects
        run: git lfs pull

      - name: Set up database
        env:
          DATABASE_URL: postgres://postgres:postgres@127.0.0.1:5432/test
          RAILS_ENV: test
        run: |
          bin/rails db:drop
          bin/rails db:create
          bin/rails db:schema:load
          bin/rails db:migrate
          bin/rails db:environment:set RAILS_ENV=test
        working-directory: ./api

      - name: Run Tests
        env:
          DATABASE_URL: postgres://postgres:postgres@127.0.0.1:5432/test
          RAILS_ENV: test
          CI: true
          RSPEC_RETRY_RETRY_COUNT: 3
          ELASTICSEARCH_URL: http://localhost:9200
        run: bin/rspec --format documentation
        working-directory: ./api
